sonar.projectKey=tierra-front-juli-refactorizado
sonar.projectName=Tierra en Calma - Frontend JULI Refactorizado
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.token=squ_3808f4147c642e9de5ebd70b71f633990a4bdcf9

sonar.sources=src
sonar.tests=src

sonar.test.inclusions=src/app/pages/login/**/*.spec.ts,src/app/pages/registrar-plantas/**/*.spec.ts

sonar.inclusions=src/app/pages/login/**,src/app/pages/registrar-plantas/**,src/app/services/auth.service.ts

sonar.javascript.lcov.reportPaths=coverage/frontend/lcov.info

sonar.exclusions=node_modules/**,coverage/**,src/main.ts,src/polyfills.ts,src/**/*.module.ts,src/environments/**,src/assets/**,**/*.css,**/*.scss,src/app/pages/mis-plantas/**