sonar.projectKey=tierra-en-calma-frontend
sonar.projectName=Tierra en Calma - Frontend
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000
sonar.token=squ_24a3113ef6c09fcaaa1d92f6129688836d1be37c

sonar.sources=src
sonar.inclusions=src/app/layouts/public-layout.html,src/app/layouts/public-layout.ts,src/app/app.ts,src/app/pages/monstera/monstera.html,src/app/pages/monstera/monstera.ts
sonar.sourceEncoding=UTF-8


# Ignorar todo lo que esté entre estos comentarios
sonar.issue.ignore.block.1.beginBlockRegexp=.*SONAR-IGNORE-START.*
sonar.issue.ignore.block.1.endBlockRegexp=.*SONAR-IGNORE-END.*
