sonar.projectKey=tierra-en-calma-frontend
sonar.projectName=Tierra en Calma - Frontend
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000
sonar.token=squ_3808f4147c642e9de5ebd70b71f633990a4bdcf9

sonar.sources=src
sonar.inclusions=\
  src/app/app.ts,\
  src/app/guards/auth-guard.ts,\
  src/app/pages/login/login.ts,\
  src/app/pages/login/auth.service.ts,\
  src/app/pages/registrar-plantas/registrar-plantas.ts,\
  src/app/pages/mis-plantas/mis-plantas.ts,\
  src/app/pages/monstera/monstera.ts,\
  src/app/services/mqtt-data.service.ts,\
  src/app/layouts/public-layout.ts
sonar.sourceEncoding=UTF-8

# Reporte de Cobertura Generado por Karma
sonar.javascript.lcov.reportPaths=coverage/frontend/lcov.info
sonar.test.inclusions=**/*.spec.ts

# Ignorar todo lo que esté entre estos comentarios
sonar.issue.ignore.block.1.beginBlockRegexp=.*SONAR-IGNORE-START.*
sonar.issue.ignore.block.1.endBlockRegexp=.*SONAR-IGNORE-END.*
