sonar.projectKey=tierra-en-calma
sonar.projectName=Tierra en Calma
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000
sonar.token=squ_dea8c816cb9a30befd860b16ea04242780b32973

sonar.sources=backend,frontend/src
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/.angular/**,**/*.spec.ts
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info