sonar.projectKey=tierra-en-calma-natalia
sonar.projectName=Tierra en Calma - Natalia
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000
sonar.token=squ_24a3113ef6c09fcaaa1d92f6129688836d1be37c

# Definimos las carpetas generales
sonar.sources=backend,frontend/src

# INCLUSIONES EXCLUSIVAS: Sonar SOLO mirará estos archivos exactos y omitirá el resto
sonar.inclusions=backend/app.js,backend/server.js,backend/SimuladorSensor.js,backend/mqttService.js,backend/pkgCentralService.js,frontend/src/app/layouts/public-layout.html,frontend/src/app/layouts/public-layout.ts,frontend/src/app/app.ts,frontend/src/app/pages/monstera/monstera.html,frontend/src/app/pages/monstera/monstera.ts

sonar.sourceEncoding=UTF-8

# Reporte de cobertura generado por Karma (ng test --code-coverage)
sonar.javascript.lcov.reportPaths=frontend/coverage/frontend/lcov.info
sonar.test.inclusions=frontend/**/*.spec.ts
