sonar.projectKey=tierra-back-juli
sonar.projectName=Tierra en Calma - Backend Juliana
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.tests=.
sonar.token=squ_dea8c816cb9a30befd860b16ea04242780b32973

sonar.inclusions=server.js,app.js,**/*.test.js
sonar.exclusions=SimuladorSensor.js,cuidadosService.js,mqttService.js,pkgCentralService.js,node_modules/**,coverage/**
sonar.test.inclusions=**/*.test.js

sonar.javascript.lcov.reportPaths=coverage/lcov.infocl