sonar.projectKey=tierra-en-calma-backend
sonar.projectName=Tierra en Calma - Backend
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000
sonar.token=squ_24a3113ef6c09fcaaa1d92f6129688836d1be37c

sonar.sources=.
sonar.inclusions=app.js,server.js,SimuladorSensor.js,mqttService.js,pkgCentralService.js
sonar.sourceEncoding=UTF-8


# Ignorar todo lo que esté entre estos comentarios
sonar.issue.ignore.block.1.beginBlockRegexp=.*SONAR-IGNORE-START.*
sonar.issue.ignore.block.1.endBlockRegexp=.*SONAR-IGNORE-END.*
