sonar.projectKey=tierra-back-juli-refactorizado
sonar.projectName=Tierra en Calma - Backend JULI Refactorizado
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.token=squ_ed655ecd7d0b4f2c0d2b9040e2e84e38aa2aa6a2


sonar.sources=app.js


sonar.tests=__tests__
sonar.test.inclusions=__tests__/HU1B_*.test.js,__tests__/HU3B_*.test.js,__tests__/HU8B_*.test.js,__tests__/HU10B_*.test.js,__tests__/HU11B_*.test.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info


sonar.exclusions=node_modules/**,coverage/**,__tests__/helpers/**